name: Sync ios_rule_script

on:
  schedule:
    # 每天凌晨 2 点运行
    - cron: "0 2 * * *"
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone source repo
        run: |
          git clone --depth=1 https://github.com/blackmatrix7/ios_rule_script.git temp_repo
          rsync -av --delete temp_repo/ ./
          rm -rf temp_repo

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from blackmatrix7/ios_rule_script" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
